### ISSUE TITLE
Error-prone use of an array as a key-value object

### ISSUE THREAD

**Issue by axelpale** [kaesetoast/find-in-files#11]
Look at the function `getResults` starting on [line 69](https://github.com/kaesetoast/find-in-files/blob/master/index.js#L69) and how the `results` array is used as a key-value data structure:

```
function getResults(content) {
    var results = []

    for (var i = 0; i < content.length; i++) {
        var fileMatch = content[i].value;
        if (fileMatch.match !== null) {
            results[fileMatch.filename] = {
                matches: fileMatch.match,
                count: fileMatch.match.length,
                line: fileMatch.lines
            };
        }
    }

    return results;
}
```

Although being valid JavaScript, this seems quite unconventional and leads to weird behaviour. For example, `results.length` equals zero. Is this a programming error? If the author intended to preserve the order, this is not the way how to do it. Arrays are objects and the order of the keys of an object is unspecified.

I guess there are two solutions. The first is simply `var results = {}`. The second option would be to still use an array but instead push objects into it, with additional key `filename`:

```
results.push({
  filename: fileMatch.filename,
  matches: fileMatch.match,
  count: fileMatch.match.length,
  line: fileMatch.lines
});
```

**Comment by kaesetoast** [comment]
Thanks for pointing this out, I agree with you here. I'll try to handle this as soon as I can. A PR would be most welcome, time is a rare resource atm :-)

**Comment by axelpale** [comment]
Thanks for taking action! Unfortunately I am incapable to make a PR: time is precious and also the issue affects the API, that I think it is up to you to decide. Yet, to help in the decision, I believe `var results = {}` has the smallest probability to cause backward-incompatibility problems.

**Comment by kaesetoast** [comment]
Thanks for the input – I'll try to handle it as soon as possible :-)

**Comment by axelpale** [comment]
Oh, all hail to @kaesetoast! :)
