### ISSUE TITLE
Possible to move on after first hit?

### ISSUE THREAD

**Issue by areknow** [kaesetoast/find-in-files#6]
Hi, thank you for this great package. 

Would it be possible to end a search as soon as the string is found once? I am comparing a list of strings to a list of files, and I have no need to know if the string is found more than the first hit.

Thank you

**Comment by kaesetoast** [comment]
Hi,

thanks for the report. I think that should be possible. I try to handle that as soon as I find the time. But right now, I can't really tell when that will be, as I am pretty busy at the moment. But you are very welcome to submit a Pull-Request :-)

Greets, Philipp

**Comment by areknow** [comment]
Thanks for the reply. 

I found a solution by using 'fs' and 'glob' then iterating over each file, and then breaking out of the loop when a file matched the string.

Cheers

**Comment by anjil** [comment]
@areknow 

"Thanks for the reply.

I found a solution by using 'fs' and 'glob' then iterating over each file, and then breaking out of the loop when a file matched the string.

Cheers"

Can you please share the example or sample code?

Thanks :)

**Comment by areknow** [comment]
@anjil I wrote the code a long time ago, so I really don't remember what my original issue was about. Here is the code: https://github.com/areknow/electron-profile/blob/master/app/js/render.js
